title: "90nwyn"
description: "偷得浮生半日闲"
url: "https://90nwyn.github.io/"
baseurl: ""
author: "90nwyn"
paginate: 5
paginate_path: "/blog/page:num/"
exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-mdui.gemspec
  - LICENSE.txt
  - README.md
  - vendor
  - docs