permalink: /:year:month:day/:title
url: https://90nwyn.github.io #Your url here
baseurl: /project

# variables
name: 90NWYN in 1995
description: 90NWYN's Data
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true